---
# Backup task
- name: Copy the configuration file of each HUAWEI S5700/S5720 Switch and put it in a .cfg file
  ce_config:
    backup: yes
    backup_options:
      filename: "{{ inventory_hostname }}.cfg"
      dir_path: /mnt/c/bkp_{{ hostvars.localhost.DTG }}/Switches/