---
### BACKUP SWITCHES CISCO - João Vitor Costa Medeiros
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Coleta o ANO, MÊS e DIA.
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
    
    - name: Aloca a data de hoje em uma variável.
      set_fact:
        DTG: "{{ ansible_date_time.date }}"

    - name: Cria o diretório C:\bkp_"ano-mês-dia"\Switches\
      file:
        path: /mnt/c/bkp_{{ hostvars.localhost.DTG }}/Switches/
        state: directory
  run_once: true

# BACKUP SWITCHES CISCO

- name: BACKUP DOS SWITCHES CISCO 2960
  hosts: switches_cisco
  gather_facts: false

  tasks:
    - name: Copia o arquivo de configuração dos switches Cisco 2960 e transforma em arquivo .cfg
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: /mnt/c/bkp_{{ hostvars.localhost.DTG }}/Switches/
