---
### MOSTRAR RESULTADOS DE COMANDO

- hosts: switches_cisco
  gather_facts: false

  tasks:
    - name: Executa comandos de "Show" no switch Cisco
      block:
      - name: 1ยบ Passo - Mostrar interfaces
        cli_command:
          command: show ip int brief
        register: result

      - name: Mostra os resultados
        debug:
          var: result.stdout_lines
      when: ansible_network_os == 'ios'