### ACCESS-LIST CISCO - João Vitor Costa Medeiros
---
- hosts: switches_cisco
  gather_facts: false

  tasks:
    - name: Remove ACL dos Switches Cisco 2960
      ios_config:
        commands:
          - no ip access-list extended ACL-POSTURE-REDIRECT

    - name: Configura ACL dos Switches Cisco 2960
      ios_config:
        commands:
          - ip access-list extended ACL-POSTURE-REDIRECT
          - deny udp any eq bootpc any eq bootps
          - deny udp any any eq domain
          - permit tcp any host 10.222.176.24 eq www
          - permit tcp any host 10.123.6.200 eq www 
          - permit tcp any host 72.163.1.80
          - deny ip any any
        save_when: modified