### ACCESS-LIST SWITCHES HUAWEI - João Vitor Costa Medeiros
- hosts: switches_huawei
  gather_facts: false

  tasks:
    - name: Apply Network Access Control Configuration to Fix ISE Server Communication Issues.
      ce_command:
        commands:
          - system-view
          - aaa
          - accounting-scheme acco
          - accounting realtime 1440
          - quit
          - #
          - radius-server template radius-dot1x
          - radius-server detect-server interval 180
          - radius-server dead-time 60
          - radius-server retransmit 4 timeout 10
          - #
          - radius-server template radius-mab
          - radius-server detect-server interval 180
          - radius-server dead-time 60
          - radius-server retransmit 4 timeout 10
          - quit

    - name: Save running-config - Switch Huawei S5700
      ce_config:
        save: yes