### ACCESS-LIST ROTEADOR HUAWEI - João Vitor Costa Medeiros
- hosts: routers_huawei
  gather_facts: false

  tasks:
    - name: Corrige ACL do Roteador Huawei S5700
      ce_command:
        commands:
          - system-view
          - undo acl name GER_REDE_RW
          - acl name GER_REDE_RW 2666
          - step 10
          - rule 10 permit source 10.123.38.186 0
          - rule 20 permit source 10.96.5.42 0
          - rule 30 permit source 10.96.5.39 0
          - rule 40 permit source 10.123.10.113 0
          - rule 50 permit source 10.0.240.250 0
          - rule 60 permit source 10.122.80.0 0.0.0.127
          - rule 70 permit source 10.123.42.253 0
          - rule 80 permit source 10.123.42.254 0
          - rule 90 permit source 10.123.42.242 0
          - rule 100 permit source 10.123.42.243 0
          - rule 110 permit source 10.123.42.244 0
          - rule 200 deny logging