### NAC SWITCHES HUAWEI - João Vitor Costa Medeiros
- hosts: switches_huawei
  gather_facts: false

  tasks:
    - name: Apply Network Access Control Configuration to Fix ISE Server Communication Issues.
      ce_command:
        commands:
          - system-view
          - acl name ISE_RO 2667
          - rule 16 permit source 10.222.179.200 0
          - rule 17 permit source 10.123.6.200 0
          - rule 18 permit source 10.123.48.24 0
          - rule 19 permit source 10.123.48.25 0
          - rule 28 permit source 10.222.176.24 0
          - rule 29 permit source 10.222.176.25 0
          - rule 100 deny

    - name: Save running-config - Switch Huawei S5700
      ce_config:
        save: yes