### DHCP ROTEADOR HUAWEI - João Vitor Costa Medeiros
- hosts: routers_huawei
  gather_facts: false

  tasks:
    - name: Update DHCP on Huawei Routers
      ce_command:
        commands:
          - system-view
          - dhcp server group 1
          - undo dhcp-server 10.123.11.30
          - undo dhcp-server 10.123.11.31
          - quit