### NAC ROLLBACK SWITCHES HUAWEI - João Vitor Costa Medeiros
- hosts: switches_huawei
  gather_facts: false

  tasks:
    - name: Apply Network Access Control Rollback Configuration.
      ce_command:
        commands:
          - system-view
          - radius-server template radius-mab
          - radius-server retransmit 2 timeout 7
          - radius-server template radius-dot1x
          - radius-server retransmit 2 timeout 7

    - name: Save running-config - Switch Huawei S5700
      ce_config:
        save: yes