### ACCESS-LIST ROTEADOR HUAWEI - João Vitor Costa Medeiros
- hosts: routers_huawei
  gather_facts: false

  tasks:
    - name: Corrige ACL do Roteador Huawei S5700
      ce_command:
        commands:
          - system-view
          - acl number 2002
          - rule 0 permit source 10.0.240.250 0
          - rule 1 permit source 10.1.32.18 0
          - rule 2 permit source 10.123.20.75 0
          - rule 3 permit source 10.0.240.136 0
          - rule 4 permit source 10.0.240.137 0
          - rule 5 permit source 10.112.9.53 0
          - rule 6 permit source 10.0.26.115 0
          - rule 7 permit source 10.0.10.148 0
          - rule 8 permit source 10.0.10.149 0
          - rule 9 permit source 10.0.10.164 0
          - rule 10 deny source any logging