---
### FULL BACKUP - João Vitor Costa Medeiros
- name: CRIA A PASTA "C:\BKP_ANO-MES-DIA" COM AS SUBPASTAS "ROUTERS" E "SWITCHES".
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Coleta o ANO, MÊS e DIA.
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
    
    - name: Aloca a data de hoje em uma variável.
      set_fact:
        DTG: "{{ ansible_date_time.date }}"

    - name: Cria as pastas "Routers" e "Switches", dentro do diretório C:\bkp_{{ hostvars.localhost.DTG }}\
      file:
        path: "/mnt/c/bkp_{{ hostvars.localhost.DTG }}/{{ item }}/"
        state: directory
      loop:
        - Routers
        - Switches
  run_once: true

# BACKUP ROTEADORES HUAWEI

- name: BACKUP DOS ROTEADORES HUAWEI AR1220
  hosts: routers_huawei
  gather_facts: false

  tasks:
    - name: Insere o comando "display current-configuration" nos roteadores e faz coleta das configurações
      cli_command:
        command: display current-configuration
      register: config

    - name: Salva as configurações dos roteadores em arquivos .cfg
      copy:
        content: "{{ config.stdout }}"
        dest: "/mnt/c/bkp_{{ hostvars.localhost.DTG }}/Routers/{{ inventory_hostname }}.cfg"
        mode: '0644'

# BACKUP SWITCHES HUAWEI

- name: BACKUP DOS SWITCHES HUAWEI S5700
  hosts: switches_huawei
  gather_facts: false

  tasks:
    - name: Copia o arquivo de configuração dos switches Huawei S5700 e transforma em arquivo .cfg
      ce_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: /mnt/c/bkp_{{ hostvars.localhost.DTG }}/Switches/

# BACKUP SWITCHES CISCO

- name: BACKUP DOS SWITCHES CISCO 2960
  hosts: switches_cisco
  gather_facts: false

  tasks:
    - name: Copia o arquivo de configuração dos switches Cisco 2960 e transforma em arquivo .cfg
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: /mnt/c/bkp_{{ hostvars.localhost.DTG }}/Switches/