---
### BANNER MOTD UPDATE - João Vitor Costa Medeiros - p696473
- hosts: switches_cisco
  gather_facts: false

  tasks:
    - name: Configura o Banner de Login
      ios_banner:
        banner: motd
        text: |
          .
                                         )!(
                                        (o o)
          +-------------------------ooO--(_)--Ooo------------------------+
          |                                                              |
          |                    * * * A T E N C A O * * *                 |
          |              ACESSO RESTRITO A PESSOAS AUTORIZADAS           |
          |     TODOS OS ACESSOS ESTAO SENDO MONITORADOS E REGISTRADOS   |
          |                                                              |
          |                    === A T T E N T I O N ===                 |
          |              THIS IS A RESTRICTED ACCESS EQUIPMENT           |
          |             ANY CONNECTIONS ARE MONITORED AND LOGGED         |
          |                                                              |
          +--------------------------------------------------------------+                             
        state: present