---
### COLETA MODELO E Nº SÉRIE - João Vitor Costa Medeiros

- name: Coleta Modelo e Nº de Série
  hosts: switches_cisco
  gather_facts: false

  tasks:
    - name: Coleta Informações do switch Cisco 2960.
      ios_facts:
        gather_subset: all

    - name: Mostra o modelo e número de série do equipamento
      debug:
        msg: "{{ ansible_net_hostname }}: Switch Cisco modelo {{ ansible_net_model }}. Nº de série: {{ ansible_net_serialnum }}"