---
### CRIA DIRETÓRIO 2 - João Vitor Costa Medeiros
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Coletar o ANO, MÊS e DIA.
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
    
    - name: Aloca a data de hoje em uma variável.
      set_fact:
        DTG: "{{ ansible_date_time.date }}"

    - name: Cria as pastas "Routers" e "Switches", dentro do diretório "C:\ano-mês-dia\"
      file:
        path: "/mnt/c/bkp_{{ hostvars.localhost.DTG }}/{{ item }}/"
        state: directory
      loop:
        - Routers
        - Switches
  run_once: true