---
### BACKUP ROUTERS HUAWEI - João Vitor Costa Medeiros
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Coleta o ANO, MÊS e DIA.
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
    
    - name: Aloca a data de hoje em uma variável.
      set_fact:
        DTG: "{{ ansible_date_time.date }}"

    - name: Cria o diretório C:\bkp_"ano-mês-dia"\Routers\
      file:
        path: /mnt/c/bkp_{{ hostvars.localhost.DTG }}/Routers/
        state: directory
  run_once: true

# BACKUP ROTEADORES HUAWEI

- hosts: routers_huawei
  gather_facts: false

  tasks:
    - name: Realiza o backup dos ROTEADORES Huawei modelo AR1220
      cli_command:
        command: dis current-configuration
      register: config

    - name: Salva as configurações dos roteadores em arquivos .cfg
      copy:
        content: "{{ config.stdout }}"
        dest: "/mnt/c/bkp_{{ hostvars.localhost.DTG }}/Routers/{{ inventory_hostname }}.cfg"
        mode: '0644'
