---
### COLLECT IP ADRESSES INTERFACES TO CREATE A VAR FILES - João Vitor Costa Medeiros

- name: Collect IP Addresses - HUAWEI AR1220 Routers
  hosts: SC0019RA1
  gather_facts: false

  tasks:
    - name: Collect Interface Data from Huawei Router
      ce_facts:
        gather_subset: interfaces

    - name: Get Interfaces Variables with IPADDR filter module
      set_fact:
        Loopback0: "{{ all_ipv4_addresses.LoopBack0 | ipaddr('address') }}"
        GigabitEthernet0_0_0_10: "{{ all_ipv4_addresses['GigabitEthernet0/0/0.10'] | ipaddr('address') }}"
        GigabitEthernet0_0_0_20: "{{ all_ipv4_addresses['GigabitEthernet0/0/0.20'] | ipaddr('address') }}"
        GigabitEthernet0_0_0_590: "{{ all_ipv4_addresses['GigabitEthernet0/0/0.590'] | ipaddr('address') }}"
        GigabitEthernet0_0_0_759: "{{ all_ipv4_addresses['GigabitEthernet0/0/0.759'] | ipaddr('address') }}"

    - name: Change variables in the Jinja file and Save it.
      template:
        src: /mnt/c/model.txt.j2
        dest: /mnt/c/{{ inventory_hostname }}.txt
        owner: root
        group: root
        mode: '0644'